export const degreeType = [
  "Pre-Master",
  "Postgraduate Diploma",
  "Postgraduate Certificate",
  "PMP",
  "P.S.M.",
  "MUD",
  "MTPC",
  "MTDA",
  "MTaxDA",
  "MSWENGR",
  "MSWE",
  "MSSP & Certificate",
  "MSSE",
  "MSPH",
  "MSPE",
  "MSN",
  "MSIT",
  "MSIS/MPAff",
  "MSIS/MA",
  "MSIS",
  "MSiA",
  "MSEE",
  "MSEd",
  "MSECE",
  "MSE",
  "MSDA",
  "MSD",
  "MSCS",
  "MSCR",
  "MSCPE",
  "MSCP",
  "MSBA",
  "MSACI",
  "MSAA",
  "MS+MBA",
  "MS/MS",
  "MS/MBA",
  "MS.Ed.",
  "MS/MEng",
  "Ms",
  "MQST",
  "MPS",
  "MPH-MS",
  "MPH",
  "MPA",
  "MNS",
  "MLS",
  "MLA",
  "MITS",
  "MIS",
  "MiDAS",
  "MIBS",
  "MHIT",
  "MHID",
  "MHCI",
  "MHA/MS",
  "MHA",
  "MGIS",
  "MFA",
  "MECPS",
  "MDS",
  "MDes",
  "MDATA",
  "MDA",
  "MCST",
  "MCS",
  "MCRP",
  "MCR",
  "MCIS",
  "MCD",
  "MBT",
  "MBAn",
  "MBA/MSISA",
  "MBA/MSIS",
  "MBA/MSHI",
  "MBA/MS",
  "MBA/MHA",
  "MBA / M.Sc.",
  "MAT",
  "Master",
  "MASc",
  "MAS",
  "MAGIST",
  "MAG",
  "MAcc",
  "MAC",
  "MA/MSc",
  "MA/MPA",
  "MA/MFA",
  "MA + MLIS",
  "M.U.R.P.",
  "M.U.P.M.Sc./M.Eng.M.Sc. / MCSM.Sc. / M.S.EM.Sc. / M.Eng.M.Sc.",
  "M.S.I.T.",
  "M.S.I.S.",
  "M.S.Ed.",
  "M.S.E.E. / M.Eng.",
  "M.S.E.E.",
  "M.S.E.",
  "M.S.E",
  "M.S.C.S.E.",
  "M.S.C.P.S.",
  "M.S.A",
  "M.S., M.Eng.",
  "M.S.",
  "M.Res.",
  "M.R.P.",
  "M.P.S.",
  "M.P.P.",
  "M.P.H.",
  "M.I.S.M.",
  "M.I.S.",
  "M.I.M.S.",
  "M.H.I.",
  "M.G.I.S.",
  "M.F.A.",
  "M.F.A",
  "M.Eng./M.Sc.",
  "M.Eng.",
  "M.Ed./M.Sc.",
  "M.Ed.",
  "M.Des.",
  "M.D.A.",
  "M.D.",
  "M.C.S.",
  "M.B.A./M.Sc.",
  "M.B.A.",
  "M.Acc.",
  "M.Acc",
  "M.A.S.",
  "M.A./M.S.",
  "M.A. / M.Sc. / M.F.A",
  "M.A.",
  "LL.M.",
  "JD/MS",
  "EMPH",
  "DNP",
  "Combined Credential",
  "CERTG",
  "B.S. + M.S.",
];

export const bachelors = [
  " B.Tech",
  "B.Sc ",
  "B.Eng ",
  "B.IT",
  "BCA",
  "BA",
  "BFA",
  "B.Des",
  "B.Mus",
  "BSW",
  "BBA",
  "B.Com ",
  "B.Acc",
  "B.Fin",
  "BHM",
  "B.Nurs",
  "B.Pharm",
  "BPT",
  "BDS",
  "BHMS",
  "LLB",
  "BSL",
  "B.Ed ",
  "B.P.Ed",
  "B.Sc Ag ",
  "B.Env.Sc",
  "BJMC",
  "BMM",

  "other",
];
export const pgCourses = [
  "MA",
  "MSc",
  "MBA",
  "MEng",
  "MEd",
  "MFA",
  "MSW",
  "MPH",
  "MPA",
  "MCA",
  "MTech",
  "LLM",
  "MArch",
  "MDes",
  "MMus",
  "MPhil",
  "MPP",
  "MIR",
  "MOT",
  "MPT",
  "MLIS",
  "MJMC",
  "MHRM",
  "MFin",
  "MSc Economics"
];
export const testScores = [
  {
    name:"Graduate Record Examination",
    scores:[
      [
        {
          description: "Verbal Reasoning",
        },
        {
          description: "Quantitative Reasoning",
        },
        {
          description: "Analytical Writing Assessment",
        },
        {
          description: "Total",
        },
      ]
    ]
  },
  {
    name:"Graduate Management Admission Test",
    scores:[
      [
        
        {
          description: "Verbal Reasoning",
        },
        {
          description: "Quantitative Reasoning",
        },
        {
          description: "Analytical Writing Assessment",
        },
        {
          description: "Integrated Reasoning",
        },
        {
          description: "Total",
        },
      ]
    ]
  },
  {
    name:"Test of English as a Foreign Language",
    scores:[
      [
        {
          description: "Reading",
        },
        {
          description: "Writing",
        },
        {
          description: "Speaking",
        },
        {
          description: "Listening",
        },
        {
          description: "Total",
        },
      ]
    ]
  },
  {
    name:"International English Language Testing System",
    scores:[
      [
        {
          description: "Reading",
        },
        {
          description: "Writing",
        },
        {
          description: "Speaking",
        },
        {
          description: "Listening",
        },
        {
          description: "Total",
        },
      ]
    ]
  },
  {
    name:"Pearson Test of English",
    scores:[
      [
        {
          description: "Reading",
        },
        {
          description: "Writing",
        },
        {
          description: "Speaking",
        },
        {
          description: "Listening",
        },
        {
          description: "Total",
        },
      ]
    ]
  },
  {
    name:"Duolingo English Test",
    scores:[
      [
        {
          description: "Literacy",
        },
        {
          description: "Conversation",
        },
        {
          description: "Comprehension",
        },
        {
          description: "production",
        },
        {
          description: "Total",
        },
      ]
    ]
  }
]
export const diplomaCourses = [
  "Diploma in Computer Science",
  "Diploma in Electrical Engineering",
  "Diploma in Mechanical Engineering",
  "Diploma in Civil Engineering",
  "Diploma in Information Technology",
  "Diploma in Nursing",
  "Diploma in Business Administration",
  "Diploma in Accounting",
  "Diploma in Hospitality Management",
  "Diploma in Graphic Design",
  "Diploma in Multimedia",
  "Diploma in Digital Marketing",
  "Diploma in Early Childhood Education",
  "Diploma in Fashion Design",
  // Add more diploma courses as needed
];



export const disciplines = [
  "Agriculture & Forestry",
  "Applied Sciences & Professions",
  "Arts, Design & Architecture",
  "Business & Management",
  "Computer Science & IT",
  "Education & Training",
  "Engineering & Technology",
  "Environmental Studies & Earth Sciences",
  "Hospitality, Leisure & Sports",
  "Humanities",
  "Journalism & Media",
  "Law",
  "Medicine & Health",
  "Natural Sciences & Mathematics",
  "Social Sciences",
];

export const subDisciplines = [
  'Agriculture',
'Animal Science',
'Food Technology',
'Forestry',
'Horticulture and Crop Science',
'Marine Science',
'Aviation Studies',
'Emergency & Disaster Management',
'Family & Consumer Science',
'Fashion, Textiles and Luxury Goods',
'Food Science',
'Forensic Science',
'Library Science',
'Military Science',
'Museum Studies',
'Real Estate & Property Management',
'Social Work',
'Architecture',
'Art and Craft',
'Art History',
'Ceramics and Sculpture',
'Dance',
'Design',
'Drama',
'Fashion Design',
'Film Studies',
'Fine Arts',
'Graphic Design',
'Industrial Design',
'Interior Design',
'Landscape Architecture',
'Music',
'Music Composition',
'Music Performance',
'Musicology',
'Painting & Drawing',
'Photography',
'Urban Planning',
'Visual Arts',
'Accounting',
'Actuarial Science',
'Advertising',
'Agribusiness',
'Auditing',
'Banking',
'Business Administration',
'Business Intelligence',
'Commerce',
'Construction Management',
'Corporate Communication',
'Corporate Social Responsibility',
'Digital Marketing',
'Digital Media',
'Engineering Management',
'Entrepreneurship',
'Executive MBA',
'Fashion Management',
'Finance',
'Financial Management',
'Financial Technology',
'Forensic Accounting',
'Human Resource Management',
'Innovation Management',
'Insurance',
'International Business',
'Investment',
'IT Management',
'Leadership',
'Management of Creative Industries',
'Management Studies',
'Marketing',
'Marketing Management',
'Master in Business Administration (MBA)',
'Master in Management (MIM)',
'Operations and Quality Management',
'Project Management',
'Public Administration',
'Retail Management',
'Risk Management',
'Strategic Management',
'Supply Chain Management & Logistics',
'Taxation',
'Transport Management',
'Animation',
'Artificial Intelligence',
'Business Information Systems',
'Computer Sciences',
'Cyber Security',
'Data Analytics',
'Data Science & Big Data',
'Game Design',
'Geographical Information Systems (GIS)',
'Health Informatics',
'Human Computer Interaction',
'Information Systems',
'Information Technology (IT)',
'Machine Learning',
'Software Engineering',
'User Experience Design',
'Web Technologies & Cloud',
'Adult Education',
'Art Education',
'Coaching',
'Early Childhood Education',
'Education',
'Educational Leadership',
'Educational Psychology',
'Educational Research',
'Health Education',
'Higher Education',
'Instructional Design',
'Literacy Education',
'Primary Education',
'School Counselling',
'Secondary Education',
'Special Education',
'STEM Education',
'Teaching',
'Teaching English as a Foreign Language',
'Aerospace Engineering',
'Automotive Engineering',
'Bio & Biomedical Engineering',
'Chemical Engineering',
'Civil Engineering & Construction',
'Communications Engineering',
'Electrical Engineering',
'Electronics & Embedded Technology',
'Energy Engineering',
'Environmental Engineering',
'General Engineering & Technology',
'Industrial & Systems Engineering',
'Marine Engineering',
'Materials Science',
'Mechanical Engineering',
'Mechatronics',
'Mining, Oil & Gas',
'Nuclear Engineering',
'Production and Manufacturing Engineering',
'Robotics',
'Sound Engineering',
'Structural Engineering',
'Sustainable Energy',
'Transportation Engineering',
'Biodiversity & Conservation',
'Climate Studies & Meteorology',
'Earth Sciences',
'Ecology',
'Environmental Economics & Policy',
'Environmental Management',
'Environmental Sciences',
'Geology',
'Hydrology & Water Management',
'Natural Resource Management',
'Soil Science',
'Sustainable Development',
'Toxicology',
'Culinary Arts',
'Event Management',
'Hospitality Management',
'Sport and Exercise Science',
'Sports Management',
'Tourism & Leisure',
'Ancient History',
'Christian Studies',
'Classics',
'Creative Writing',
'ESL',
'Ethics',
'General Studies',
'History',
'Islamic Studies',
'Language Studies',
'Liberal Arts',
'Linguistics',
'Literature',
'Modern History',
'Philosophy',
'Theology and Religious Studies',
'Journalism',
'Media Management',
'Media Studies & Mass Media',
'Public Relations',
'Publishing',
'Translation & Interpreting',
'Business Law',
'Civil & Private Law',
'Criminal Justice',
'Criminal Law',
'European Law',
'International Law',
'Legal Studies',
'Master of Laws (LLM)',
'Patent & Intellectual Property Law',
'Public Law',
'Biomedical Science',
'Clinical Psychology',
'Complementary & Alternative Medicine',
'Dentistry',
'Epidemiology',
'Gerontology',
'Health Administration',
'Health Sciences',
'Immunology',
'Kinesiology',
'Medical Imaging',
'Medicine',
'Midwifery',
'Nursing',
'Nutrition & Dietetics',
'Occupational Health and Safety',
'Occupational Therapy',
'Optometry',
'Pathology',
'Pharmacy',
'Physiology',
'Physiotherapy',
'Prosthetics and Orthotics',
'Public Health',
'Speech Pathology',
'Veterinary Medicine',
'Anatomy',
'Applied Mathematics',
'Astronomy & Space Sciences',
'Biochemistry',
'Bioinformatics & Biostatistics',
'Biology',
'Biotechnology',
'Botany',
'Chemistry',
'Computational Mathematics',
'Financial Mathematics',
'Genetics',
'Mathematics',
'Microbiology',
'Molecular Sciences',
'Nanoscience and Nanotechnology',
'Natural Sciences',
'Neuroscience',
'Oceanography',
'Operations Research',
'Pharmacology',
'Physics',
'Statistics',
'Zoology',
'African Studies',
'American and Australasian studies',
'Anthropology',
'Archaeology',
'Area & Cultural Studies',
'Art Therapy',
'Asian Studies',
'Childhood Studies',
'Cognitive Science',
'Communication Studies',
'Community Development',
'Counselling Psychology',
'Criminology',
'Developmental Psychology',
'Diplomacy',
'Econometrics',
'Economics',
'Ethnic Studies',
'European Studies',
'Forensic Psychology',
'French Studies',
'Gender & Sexuality Studies',
'Geography',
'German and Scandinavian Studies',
'Iberian Studies',
'International Development',
'International Relations',
'Italian Studies',
'Middle Eastern Studies',
'Organisational Behaviour',
'Political Science',
'Psychology',
'Public Policy',
'Slavic Studies',
'Social Policy',
'Social Psychology',
'Sociology',
'Terrorism & Security',
];

export const law = [
  'Business Law',
  'Civil & Private Law',
  'Criminal Justice',
  'Criminal Law',
  'European Law',
  'International Law',
  'Legal Studies',
  'Master of Laws (LLM)',
  'Patent & Intellectual Property Law',
  'Public Law',
]
export const socialScience = [
  'African Studies',
'American and Australasian studies',
'Anthropology',
'Archaeology',
'Area & Cultural Studies',
'Art Therapy',
'Asian Studies',
'Childhood Studies',
'Cognitive Science',
'Communication Studies',
'Community Development',
'Counselling Psychology',
'Criminology',
'Developmental Psychology',
'Diplomacy',
'Econometrics',
'Economics',
'Ethnic Studies',
'European Studies',
'Forensic Psychology',
'French Studies',
'Gender & Sexuality Studies',
'Geography',
'German and Scandinavian Studies',
'Iberian Studies',
'International Development',
'International Relations',
'Italian Studies',
'Middle Eastern Studies',
'Organisational Behaviour',
'Political Science',
'Psychology',
'Public Policy',
'Slavic Studies',
'Social Policy',
'Social Psychology',
'Sociology',
'Terrorism & Security',
]
export const medicine = [
  'Biomedical Science',
  'Clinical Psychology',
  'Complementary & Alternative Medicine',
  'Dentistry',
  'Epidemiology',
  'Gerontology',
  'Health Administration',
  'Health Sciences',
  'Immunology',
  'Kinesiology',
  'Medical Imaging',
  'Medicine',
  'Midwifery',
  'Nursing',
  'Nutrition & Dietetics',
  'Occupational Health and Safety',
  'Occupational Therapy',
  'Optometry',
  'Pathology',
  'Pharmacy',
  'Physiology',
  'Physiotherapy',
  'Prosthetics and Orthotics',
  'Public Health',
  'Speech Pathology',
  'Veterinary Medicine',
  
]
export const naturalScience = [
  'Anatomy',
  'Applied Mathematics',
  'Astronomy & Space Sciences',
  'Biochemistry',
  'Bioinformatics & Biostatistics',
  'Biology',
  'Biotechnology',
  'Botany',
  'Chemistry',
  'Computational Mathematics',
  'Financial Mathematics',
  'Genetics',
  'Mathematics',
  'Microbiology',
  'Molecular Sciences',
  'Nanoscience and Nanotechnology',
  'Natural Sciences',
  'Neuroscience',
  'Oceanography',
  'Operations Research',
  'Pharmacology',
  'Physics',
  'Statistics',
  'Zoology',
]

export const hospitality = [
  'Culinary Arts',
  'Event Management',
  'Hospitality Management',
  'Sport and Exercise Science',
  'Sports Management',
  'Tourism & Leisure',
]
export const journalism = [
  'Journalism',
'Media Management',
'Media Studies & Mass Media',
'Public Relations',
'Publishing',
'Translation & Interpreting',
]
export const humanity = [
  'Ancient History',
'Christian Studies',
'Classics',
'Creative Writing',
'ESL',
'Ethics',
'General Studies',
'History',
'Islamic Studies',
'Language Studies',
'Liberal Arts',
'Linguistics',
'Literature',
'Modern History',
'Philosophy',
'Theology and Religious Studies',
]
export const education = [
  'Adult Education',
  'Art Education',
  'Coaching',
  'Early Childhood Education',
  'Education',
  'Educational Leadership',
  'Educational Psychology',
  'Educational Research',
  'Health Education',
  'Higher Education',
  'Instructional Design',
  'Literacy Education',
  'Primary Education',
  'School Counselling',
  'Secondary Education',
  'Special Education',
  'STEM Education',
  'Teaching',
  'Teaching English as a Foreign Language',
]
export const environmental = [
  'Biodiversity & Conservation',
  'Climate Studies & Meteorology',
  'Earth Sciences',
  'Ecology',
  'Environmental Economics & Policy',
  'Environmental Management',
  'Environmental Sciences',
  'Geology',
  'Hydrology & Water Management',
  'Natural Resource Management',
  'Soil Science',
  'Sustainable Development',
  'Toxicology',
]
export const engineering = [
  'Aerospace Engineering',
'Automotive Engineering',
'Bio & Biomedical Engineering',
'Chemical Engineering',
'Civil Engineering & Construction',
'Communications Engineering',
'Electrical Engineering',
'Electronics & Embedded Technology',
'Energy Engineering',
'Environmental Engineering',
'General Engineering & Technology',
'Industrial & Systems Engineering',
'Marine Engineering',
'Materials Science',
'Mechanical Engineering',
'Mechatronics',
'Mining, Oil & Gas',
'Nuclear Engineering',
'Production and Manufacturing Engineering',
'Robotics',
'Sound Engineering',
'Structural Engineering',
'Sustainable Energy',
'Transportation Engineering',
]

export const agriculture = [
  'Agriculture',
'Animal Science',
'Food Technology',
'Forestry',
'Horticulture and Crop Science',
'Marine Science',
]

export const appliedSciences = [
  'Aviation Studies',
'Emergency & Disaster Management',
'Family & Consumer Science',
'Fashion, Textiles and Luxury Goods',
'Food Science',
'Forensic Science',
'Library Science',
'Military Science',
'Museum Studies',
'Real Estate & Property Management',
'Social Work',
]

export const artsDesign = [
  'Architecture',
  'Art and Craft',
  'Art History',
  'Ceramics and Sculpture',
  'Dance',
  'Design',
  'Drama',
  'Fashion Design',
  'Film Studies',
  'Fine Arts',
  'Graphic Design',
  'Industrial Design',
  'Interior Design',
  'Landscape Architecture',
  'Music',
  'Music Composition',
  'Music Performance',
  'Musicology',
  'Painting & Drawing',
  'Photography',
  'Urban Planning',
  'Visual Arts',
]
export const businessManagement = [
  'Accounting',
'Actuarial Science',
'Advertising',
'Agribusiness',
'Auditing',
'Banking',
'Business Administration',
'Business Intelligence',
'Commerce',
'Construction Management',
'Corporate Communication',
'Corporate Social Responsibility',
'Digital Marketing',
'Digital Media',
'Engineering Management',
'Entrepreneurship',
'Executive MBA',
'Fashion Management',
'Finance',
'Financial Management',
'Financial Technology',
'Forensic Accounting',
'Human Resource Management',
'Innovation Management',
'Insurance',
'International Business',
'Investment',
'IT Management',
'Leadership',
'Management of Creative Industries',
'Management Studies',
'Marketing',
'Marketing Management',
'Master in Business Administration (MBA)',
'Master in Management (MIM)',
'Operations and Quality Management',
'Project Management',
'Public Administration',
'Retail Management',
'Risk Management',
'Strategic Management',
'Supply Chain Management & Logistics',
'Taxation',
'Transport Management',
]

export const computerScience = [
  'Animation',
  'Artificial Intelligence',
  'Business Information Systems',
  'Computer Sciences',
  'Cyber Security',
  'Data Analytics',
  'Data Science & Big Data',
  'Game Design',
  'Geographical Information Systems (GIS)',
  'Health Informatics',
  'Human Computer Interaction',
  'Information Systems',
  'Information Technology (IT)',
  'Machine Learning',
  'Software Engineering',
  'User Experience Design',
  'Web Technologies & Cloud',
]

export const skillsList = [
  "Full Stack Application Development",
  "Software Development",
  "Frontend Development",
  "Backend Development",
  "Marketing Head",
  "Research Skills",
  "Critical Thinking",
  "Communication Skills",
  "Analytical Skills",
  "Time Management",
  "Adaptability",
  "Teamwork and Collaboration",
  "Problem-Solving",
  "Independent Learning",
  "Ethical and Professional Conduct",
  "Technological Proficiency",
  "Networking Skills",
  "Presentation Skills",
  "Project Management",
  "Leadership",
];
export const universityList = [
  "Abhilashi University,Himachal Pradesh",
  "Academy Of Maritime Education And Training, Tamil Nadu",
  "Academy Of Scientific And Innovative Research,Ghaziabad",
  "Acharya N G Ranga Agricultural University,Hyderabad",
  "Acharya Nagarjuna University,Guntur",
  "Adikavi Nannaya University,Andhra Pradesh",
  "AISECT University, Jharkhand",
  "Ajeenkya DY Patil University,Pune",
  "Alagappa University",
  "Aligarh Muslim University",
  "All India Institute Of Medical Sciences (AIIMS),Delhi",
  "Amity Business School, Noida",
  "Amity University Gurugram",
  "Amity University Jaipur",
  "Amity University Noida",
  "Amity Universiy,Manesar",
  "Amrita Vishwa Vidyapeetham",
  "Andhra University",
  "Anna University",
  "Annamalai University",
  "Anurag Group of Institutions",
  "Apeejay School Of Management ,Delhi",
  "Appejay School Of Marketing,New Delhi",
  "Ashoka University",
  "Assam University",
  "Avinashilingam Institute for Home Science & Higher Education for Women",
  "Baba Farid University Of Health Sciences,Punjab",
  "Babasheb Bhimrao Ambedkar University",
  "Banaras Hindu University",
  "Banasthali Vidyapith",
  "Bangalore University, Bengaluru",
  "Bangalore University,Bengaluru",
  "Barkatullah Vishwavidyalaya,Bhopal",
  "Bengaluru City University,Bangalore",
  "Bhakta Kavi Narsinh Mehta University,Dungarpur",
  "Bharath Institute of Higher Education & Research",
  "Bharathiar University",
  "Bharathidasan University",
  "Bharati Vidyapeeth",
  "Biju Patnaik University Of Technology,Rourkela, Odisha",
  "Birla Institute of Technology",
  "Birla Institute of Technology & Science",
  "Calcutta University",
  "Calicut University",
  "Central Institute Of Fisheries Education,Mumbai",
  "Central University Of Gujarat, Gandhinagar",
  "Central University Of Karnataka,Gulbarga",
  "Central University of Kerala",
  "Central University of Punjab",
  "Central University of Tamil Nadu",
  "Chandigarh University, Chandigarh",
  "Chandigarh University,Mohali",
  "Chaudhary Charan Singh University,Meerut",
  "Chaudhary Devi Lal University,Sirsa",
  "Chettinad Academy of Research and Education",
  "Chitkara University, Rajpura",
  "Christ University,Banglore",
  "Cochin University of Science and Technology",
  "Coimbatore Institute of Technology",
  "College of Engineering Pune",
  "D Y Patil Educational Society",
  "Datta Meghe Institute of Medical Sciences",
  "Dayalbagh Educational Institute",
  "Dayanand Sagar University,Bangluru",
  "Delhi Institute Of Hotel Management & Catering Technology,Delhi",
  "Delhi Technological University",
  "Devi Ahilya Vishwavidyalaya, Indore",
  "Dharmsinh Desai University",
  "Dibrugarh University",
  "DIT University, Mussoorie",
  "Dr APJ Abdul Kalam Technical University, Uttar Pradesh",
  "Dr APJ Abdul Kalam University, Indore",
  "Dr Babasaheb Ambedkar Marathwada University",
  "Dr CV Raman University, Chattisgarh",
  "Dr DY Patil Vidyapeeth",
  "Dr Ntr University Of Health Sciences, Andhra Pradesh",
  "Dr Vishwanath Karad MIT-WPU, Pune",
  "Dr Babasaheb Ambedkar Technological University, Maharashtra",
  "English & Foreign Languages University",
  "Galgotias University, Noida",
  "Gandhi Institute of Technology and Management",
  "Ganpat University, Gujarat",
  "Gauhati University",
  "Gautam Buddh Technical University, Lucknow",
  "Goa University",
  "Gondwana University, Gadchiroli",
  "Government College of Technology",
  "Graphic Era University",
  "Gujarat Technological University",
  "Gujarat University",
  "Guru Gobind Singh Indraprastha University",
  "Guru Jambheshwar University of Science and Technology",
  "Guru Nanak Dev University",
  "Hemchandracharya North Gujarat University, Gujarat",
  "Hemvati Nandan Bahuguna Garhwal University, Srinagar, Uttarakhand",
  "Himachal Pradesh University, Shimla",
  "Himalayan Garhwal University, Uttarakhand",
  "Hindustan Institute Of Technology And Science, New Delhi",
  "Homi Bhabha National Institute",
  "ICFAI Foundation For Higher Education, Hyderabad",
  "IEC University, Himachal Pradesh",
  "IIHMR University, Jaipur",
  "IK Gujral Punjab Technical University, Punjab",
  "Indian Institute of Engineering Science and Technology",
  "Indian Institute Of Management Ahmedabad, Ahmedabad",
  "Indian Institute of Science",
  "Indian Institute of Science Education & Research Bhopal",
  "Indian Institute of Science Education & Research Kolkata",
  "Indian Institute of Science Education & Research Mohali",
  "Indian Institute of Science Education & Research Pune",
  "Indian Institute of Science Education & Research Thiruvananthapuram",
  "Indian Institute of Technology (BHU) Varanasi",
  "Indian Institute of Technology (Indian School of Mines)",
  "Indian Institute of Technology (Others)",
  "Indian Institute of Technology Bhubaneswar",
  "Indian Institute of Technology Bombay",
  "Indian Institute of Technology Delhi",
  "Indian Institute of Technology Gandhinagar",
  "Indian Institute of Technology Guwahati",
  "Indian Institute of Technology Hyderabad",
  "Indian Institute of Technology Indore",
  "Indian Institute of Technology Kanpur",
  "Indian Institute of Technology Kharagpur",
  "Indian Institute of Technology Madras",
  "Indian Institute of Technology Mandi",
  "Indian Institute of Technology Patna",
  "Indian Institute of Technology Roorkee",
  "Indian Institute of Technology Ropar",
  "Indian Institute of Technology Tirupati",
  "Indira Gandhi National Open University, Uttar Pradesh",
  "Indraprastha Institute of Information Technology Delhi",
  "Institute of Chemical Technology",
  "International Institute of Information Technology Hyderabad",
  "Invertis University, Bareilly",
  "Jadavpur University",
  "Jai Narain Vyas University, Jodhpur",
  "Jain University",
  "Jaipur National University, Jaipur",
  "Jamia Hamdard",
  "Jamia Millia Islamia",
  "Jawaharlal Nehru Architecture And Fine Arts University, Hyderabad",
  "Jawaharlal Nehru Technological University",
  "Jawaharlal Nehru University",
  "Jaypee Institute of Information Technology",
  "Jaypee University of Information Technology",
  "Jiwaji University, Gwalior",
  "Jodhpur National University, Jodhpur",
  "JSS Academy of Higher Education and Research",
  "JSS Science and Technology University",
  "Kadi Sarva Vishwavidyalaya, Gujarat",
  "Kakatiya University, Warangal",
  "Kalasalingam Academy of Research and Higher Education",
  "Kalinga Institute of Industrial Technology",
  "Kalinga University, Chhattisgarh",
  "Kalyani University",
  "Kannur University, Kerala",
  "Karnataka University, Dharwad",
  "Karunya Institute of Technology and Sciences",
  "Kerala University",
  "Kerala University Of Health Sciences, Thrissur",
  "King George`s Medical University",
  "KLE Academy of Higher Education and Research",
  "KLE Technological University",
  "Konaseema Institute of Medical Sciences Research Foundation",
  "Koneru Lakshmaiah Education Foundation University",
  "Krishna Institute of Medical Sciences",
  "Krishna University, Andhra Pradesh",
  "Kumaraguru College of Technology",
  "Kumaun University, Uttarakhand",
  "Kurukshetra University",
  "Kuvempu University",
  "Lovely Professional University",
  "M G R Educational and Research Institute",
  "M S Ramaiah University Of Applied Sciences, New Delhi",
  "Madurai Kamaraj University",
  "Maharaja Ganga Singh University, Rajasthan",
  "Maharaja Krishnakumarsinhji Bhavnagar University, Bhavnagar, Gujarat",
  "Maharaja Ranjit Singh Punjab Technical University, Bathinda",
  "Maharaja Sayajirao University of Baroda",
  "Maharashtra University Of Health Sciences, Maharashtra",
  "Maharishi Markandeshwar",
  "Maharshi Dayanand University",
  "Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya, Madhya Pradesh",
  "Mahatma Gandhi University",
  "Mahatma Jyotiba Phule Rohilkhand University, Bareilly",
  "Mahatma Jyotiba Phule Rohilkhand University, Bareilley",
  "Malaviya National Institute of Technology",
  "Manav Rachna International Institute Of Research And Studies, Faridabad",
  "Mangalore University",
  "Manipal Academy of Higher Education",
  "Manipal Institute Of Technology, Manipal",
  "Manipal University Jaipur, Dahmi Kalan",
  "Manipal University, Jaipur",
  "Manipur University",
  "Maulana Abul Kalam Azad University Of Technology, West Bengal",
  "Maulana Azad National Institute of Technology",
  "Meenakshi Academy of Higher Education and Research",
  "Mepco Schlenk Engineering College",
  "Mewar University, Delhi",
  "MGM Institute of Health Sciences",
  "MIT Art, Design And Technology University, Pune",
  "Mizoram University",
  "Mohanlal Sukhadia University, Udaipur",
  "Motilal Nehru National Institute of Technology",
  "Mumbai University",
  "Mysore University",
  "N M A M Institute of Technology",
  "Nagaland University",
  "Nagpur University, Nagpur",
  "Narayana Medical College",
  "Narsee Monjee Institute Of Management Studies, Delhi",
  "National Council For Hotel Management And Catering Technology, Noida",
  "National Institute Of Fashion Technology",
  "National Institute of Industrial Engineering",
  "National Institute of Technology Durgapur",
  "National Institute of Technology Hamirpur",
  "National Institute of Technology Karnataka",
  "National Institute of Technology Patna",
  "National Institute of Technology Raipur",
  "National Institute of Technology Rourkela",
  "National Institute of Technology Silchar",
  "National Institute of Technology Tiruchirappalli",
  "National Institute of Technology Warangal",
  "Nirma University",
  "NITTE",
  "Noorul Islam Centre For Higher Education, Kanyakumari",
  "North Eastern Hill University",
  "OP Jindal Global University",
  "Osmania University",
  "P E S College of Engineering",
  "Padmashree Dr D Y Patil Vidyapeeth",
  "Pandit Bhagwat Dayal Sharma University Of Health Sciences, Rohtak, Haryana",
  "Panjab University",
  "Parul University, Vadodara",
  "Periyar University",
  "PES University",
  "Pondicherry University",
  "Pravara Institute of Medical Sciences",
  "Presidency University",
  "PRIST University, Vallam",
  "PSG College of Technology",
  "PSGR Krishnammal College for Women",
  "Pt Ravishankar Shukla University",
  "Punjab Agricultural University, Ludhiana",
  "Punjabi University",
  "Rabindranath Tagore University",
  "Rajasthan Technical University, Kota",
  "Rajiv Gandhi Proudyogiki Vishwavidyalaya, Madhya Pradesh",
  "Rajiv Gandhi University",
  "Rajiv Gandhi University Of Health Sciences, Bengaluru",
  "Reva University, Bangalore",
  "Reva University, Karnataka",
  "S R M Institute of Science and Technology",
  "Sant Gadge Baba Amravati University, Amravati, Maharashtra",
  "Sardar Patel University, Uttar Pradesh",
  "Sarvepalli Radhakrishnan University, Bhopal",
  "Sathyabama Institute of Science and Technology",
  "Sathyabama University, Chennai",
  "Saurashtra University, Rajkot",
  "Saveetha Institute of Medical and Technical Sciences",
  "Savitribai Phule Pune University",
  "Sawai Man Singh Medical College",
  "Shanmugha Arts Science Technology & Research Academy",
  "Sharda University, Noida",
  "Sharda University, Delhi",
  "Shiv Nadar University",
  "Shivaji University",
  "Shoolini University of Biotechnology and Management Sciences",
  "Shreemati Nathibai Damodar Thackersey Women's University, Mumbai",
  "Shri Mata Vaishno Devi University",
  "Shri Ramdeobaba College of Engineering and Management",
  "Sikkim Manipal University",
  "Siksha `O` Anusandhan",
  "Singhania University, Jhunjunu, Rajasthan",
  "SR Engineering College",
  "Sri Balaji Vidyapeeth Mahatma Gandhi Medical College Campus",
  "Sri Chaitanya Junior College, Ghaziabad",
  "Sri Devraj Urs Academy of Higher Education and Research",
  "Sri Krishna College of Engineering and Technology",
  "Sri Krishna College of Technology",
  "Sri Krishnadevaraya University, Anantapur",
  "Sri Ramachandra Institute of Higher Education And Research",
  "Sri Sairam Engineering College",
  "Sri Sathya Sai Institute of Higher Learning",
  "Sri Satya Sai University Of Technology And Medical Sciences, Madhya Pradesh",
  "Sri Sivasubramaniya Nadar College of Engineering",
  "Sri Venkateswara Institute of Medical Sciences",
  "Sri Venkateswara University",
  "St Xavier's University, Kolkata",
  "SVKM`s Narsee Monjee Institute of Management Studies",
  "Swami Vivekanand Subharti University, Meerut",
  "Symbiosis International",
  "Tata Institute of Social Sciences",
  "Telangana University, Nizamabad",
  "Tezpur University",
  "Thapar Institute of Engineering & Technology",
  "The Gandhigram Rural Institute",
  "The Tamil Nadu Dr MGR Medical University, Chennai",
  "The University of Burdwan",
  "Thiagarajar College of Engineering",
  "Tilka Manjhi Bhagalpur University, Bihar",
  "Tumkur University",
  "University of Delhi",
  "University of Hyderabad",
  "University of Jammu",
  "University of Kashmir",
  "University Of Lucknow, Lucknow",
  "University of Madras",
  "University Of Petroleum And Energy Studies, Dehradun",
  "University Of Petroleum And Energy Studies, Gurugram",
  "University Of Rajasthan, Jaipur",
  "Utkal University",
  "Uttarakhand Technical University, Uttarakhand",
  "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology",
  "Vardhaman College of Engineering",
  "Veer Bahadur Singh Purvanchal University, Jaunpur",
  "Veer Narmad South Gujarat University, Gujarat",
  "Veer Surendra Sai University of Technology",
  "Vel Tech Rangarajan Dr Sagunthala R & D Institute of Science and Technology",
  "Velagapudi Ramakrishna Siddhartha Engineering College",
  "Vellore Institute of Technology",
  "Vignan University, Andhra Pradesh",
  "Vignan's Foundation for Science, Technology & Research",
  "Vinayaka Mission's Research Foundation",
  "Visva Bharati",
  "Visvesvaraya National Institute Of Technology, Nagpur",
  "Visvesvaraya Technological University",
  "Yenepoya University",
  "Other",
];
export const currencySymbols = [
  "United Arab Emirates Dirham-AED",
  "Afghan Afghani-AFN",
  "Albanian Lek-ALL",
  "Armenian Dram-AMD",
  "Netherlands Antillean Guilder-ANG",
  "Angolan Kwanza-AOA",
  "Argentine Peso-ARS",
  "Australian Dollar-AUD",
  "Aruban Florin-AWG",
  "Azerbaijani Manat-AZN",
  "Bosnia Herzegovina Convertible Mark-BAM",
  "Barbadian Dollar-BBD",
  "Bangladeshi Taka-BDT",
  "Bulgarian Lev-BGN",
  "Bahraini Dinar-BHD",
  "Burundian Franc-BIF",
  "Bermudian Dollar-BMD",
  "Brunei Dollar-BND",
  "Bolivian Boliviano-BOB",
  "Brazilian Real-BRL",
  "Bahamian Dollar-BSD",
  "Bitcoin-BTC",
  "Bhutanese Ngultrum-BTN",
  "Botswanan Pula-BWP",
  "Belarusian Ruble-BYN",
  "Belize Dollar-BZD",
  "Canadian Dollar-CAD",
  "Congolese Franc-CDF",
  "Swiss Franc-CHF",
  "Chilean Unit of Account (UF)-CLF",
  "Chilean Peso-CLP",
  "Chinese Yuan Offshore-CNH",
  "Chinese Yuan-CNY",
  "Colombian Peso-COP",
  "Costa Rican Colón-CRC",
  "Cuban Convertible Peso-CUC",
  "Cuban Peso-CUP",
  "Cape Verdean Escudo-CVE",
  "Czech Republic Koruna-CZK",
  "Djiboutian Franc-DJF",
  "Danish Krone-DKK",
  "Dominican Peso-DOP",
  "Algerian Dinar-DZD",
  "Egyptian Pound-EGP",
  "Eritrean Nakfa-ERN",
  "Ethiopian Birr-ETB",
  "Euro-EUR",
  "Fijian Dollar-FJD",
  "Falkland Islands Pound-FKP",
  "British Pound Sterling-GBP",
  "Georgian Lari-GEL",
  "Guernsey Pound-GGP",
  "Ghanaian Cedi-GHS",
  "Gibraltar Pound-GIP",
  "Gambian Dalasi-GMD",
  "Guinean Franc-GNF",
  "Guatemalan Quetzal-GTQ",
  "Guyanaese Dollar-GYD",
  "Hong Kong Dollar-HKD",
  "Honduran Lempira-HNL",
  "Croatian Kuna-HRK",
  "Haitian Gourde-HTG",
  "Hungarian Forint-HUF",
  "Indonesian Rupiah-IDR",
  "Israeli New Shekel-ILS",
  "Isle of Man Pound-IMP",
  "Indian Rupee-INR",
  "Iraqi Dinar-IQD",
  "Iranian Rial-IRR",
  "Icelandic Króna-ISK",
  "Jersey Pound-JEP",
  "Jamaican Dollar-JMD",
  "Jordanian Dinar-JOD",
  "Japanese Yen-JPY",
  "Kenyan Shilling-KES",
  "Kyrgystani Som-KGS",
  "Cambodian Riel-KHR",
  "Kuwaiti Dinar-KWD",
  "Cayman Islands Dollar-KYD",
  "Kazakhstani Tenge-KZT",
  "Laotian Kip-LAK",
  "Lebanese Pound-LBP",
  "Sri Lankan Rupee-LKR",
  "Liberian Dollar-LRD",
  "Lesotho Loti-LSL",
  "Libyan Dinar-LYD",
  "Moroccan Dirham-MAD",
  "Moldovan Leu-MDL",
  "Malagasy Ariary-MGA",
  "Macedonian Denar-MKD",
  "Myanma Kyat-MMK",
  "Mongolian Tugrik-MNT",
  "Macanese Pataca-MOP",
  "Mauritanian Ouguiya-MRU",
  "Mauritian Rupee-MUR",
  "Maldivian Rufiyaa-MVR",
  "Malawian Kwacha-MWK",
  "Mexican Peso-MXN",
  "Malaysian Ringgit-MYR",
  "Mozambican Metical-MZN",
  "Namibian Dollar-NAD",
  "Nigerian Naira-NGN",
  "Nicaraguan Córdoba-NIO",
  "Norwegian Krone-NOK",
  "Nepalese Rupee-NPR",
  "New Zealand Dollar-NZD",
  "Omani Rial-OMR",
  "Panamanian Balboa-PAB",
  "Peruvian Nuevo Sol-PEN",
  "Papua New Guinean Kina-PGK",
  "Philippine Peso-PHP",
  "Pakistani Rupee-PKR",
  "Polish Zloty-PLN",
  "Paraguayan Guarani-PYG",
  "Qatari Rial-QAR",
  "Romanian Leu-RON",
  "Serbian Dinar-RSD",
  "Russian Ruble-RUB",
  "Rwandan Franc-RWF",
  "Saudi Riyal-SAR",
  "Solomon Islands Dollar-SBD",
  "Seychellois Rupee-SCR",
  "Sudanese Pound-SDG",
  "Swedish Krona-SEK",
  "Singapore Dollar-SGD",
  "Saint Helena Pound-SHP",
  "Sierra Leonean Leone-SLL",
  "Somali Shilling-SOS",
  "Surinamese Dollar-SRD",
  "South Sudanese Pound-SSP",
  "São Tomé and Príncipe Dobra-STD",
  "São Tomé and Príncipe Dobra (2020)-STN",
  "Salvadoran Colón-SVC",
  "Syrian Pound-SYP",
  "Swazi Lilangeni-SZL",
  "Thai Baht-THB",
  "Tajikistani Somoni-TJS",
  "Turkmenistani Manat-TMT",
  "Tunisian Dinar-TND",
  "Tongan Pa'anga-TOP",
  "Turkish Lira-TRY",
  "Trinidad and Tobago Dollar-TTD",
  "New Taiwan Dollar-TWD",
  "Tanzanian Shilling-TZS",
  "Ukrainian Hryvnia-UAH",
  "Ugandan Shilling-UGX",
  "United States Dollar-USD",
  "Uruguayan Peso-UYU",
  "Uzbekistan Som-UZS",
  "Venezuelan Bolívar Soberano-VES",
  "Vietnamese Dong-VND",
  "Vanuatu Vatu-VUV",
  "Samoan Tala-WST",
  "CFA Franc BEAC-XAF",
  "Silver Ounce-XAG",
  "Gold Ounce-XAU",
  "East Caribbean Dollar-XCD",
  "Special Drawing Rights-XDR",
  "CFA Franc BCEAO-XOF",
  "Palladium Ounce-XPD",
  "CFP Franc-XPF",
  "Platinum Ounce-XPT",
  "Yemeni Rial-YER",
  "South African Rand-ZAR",
  "Zambian Kwacha-ZMW",
  "Zimbabwean Dollar-ZWL"
];
export  const countryList = [
  "Australia",
  "Canada",
  "United States of America",
  "United Kingdom",
  "New Zealand",
  "Ireland",
];
export const countries = [
  { code: "AD", label: "Andorra", phone: "376" },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AF", label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", label: "Anguilla", phone: "1-264" },
  { code: "AL", label: "Albania", phone: "355" },
  { code: "AM", label: "Armenia", phone: "374" },
  { code: "AO", label: "Angola", phone: "244" },
  { code: "AQ", label: "Antarctica", phone: "672" },
  { code: "AR", label: "Argentina", phone: "54" },
  { code: "AS", label: "American Samoa", phone: "1-684" },
  { code: "AT", label: "Austria", phone: "43" },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", phone: "297" },
  { code: "AX", label: "Alland Islands", phone: "358" },
  { code: "AZ", label: "Azerbaijan", phone: "994" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", label: "Barbados", phone: "1-246" },
  { code: "BD", label: "Bangladesh", phone: "880" },
  { code: "BE", label: "Belgium", phone: "32" },
  { code: "BF", label: "Burkina Faso", phone: "226" },
  { code: "BG", label: "Bulgaria", phone: "359" },
  { code: "BH", label: "Bahrain", phone: "973" },
  { code: "BI", label: "Burundi", phone: "257" },
  { code: "BJ", label: "Benin", phone: "229" },
  { code: "BL", label: "Saint Barthelemy", phone: "590" },
  { code: "BM", label: "Bermuda", phone: "1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "673" },
  { code: "BO", label: "Bolivia", phone: "591" },
  { code: "BR", label: "Brazil", phone: "55" },
  { code: "BS", label: "Bahamas", phone: "1-242" },
  { code: "BT", label: "Bhutan", phone: "975" },
  { code: "BV", label: "Bouvet Island", phone: "47" },
  { code: "BW", label: "Botswana", phone: "267" },
  { code: "BY", label: "Belarus", phone: "375" },
  { code: "BZ", label: "Belize", phone: "501" },
  {
    code: "CA",
    label: "Canada",
    phone: "1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    phone: "242",
  },
  { code: "CH", label: "Switzerland", phone: "41" },
  { code: "CI", label: "Cote d'Ivoire", phone: "225" },
  { code: "CK", label: "Cook Islands", phone: "682" },
  { code: "CL", label: "Chile", phone: "56" },
  { code: "CM", label: "Cameroon", phone: "237" },
  { code: "CN", label: "China", phone: "86" },
  { code: "CO", label: "Colombia", phone: "57" },
  { code: "CR", label: "Costa Rica", phone: "506" },
  { code: "CU", label: "Cuba", phone: "53" },
  { code: "CV", label: "Cape Verde", phone: "238" },
  { code: "CW", label: "Curacao", phone: "599" },
  { code: "CX", label: "Christmas Island", phone: "61" },
  { code: "CY", label: "Cyprus", phone: "357" },
  { code: "CZ", label: "Czech Republic", phone: "420" },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", phone: "253" },
  { code: "DK", label: "Denmark", phone: "45" },
  { code: "DM", label: "Dominica", phone: "1-767" },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", label: "Algeria", phone: "213" },
  { code: "EC", label: "Ecuador", phone: "593" },
  { code: "EE", label: "Estonia", phone: "372" },
  { code: "EG", label: "Egypt", phone: "20" },
  { code: "EH", label: "Western Sahara", phone: "212" },
  { code: "ER", label: "Eritrea", phone: "291" },
  { code: "ES", label: "Spain", phone: "34" },
  { code: "ET", label: "Ethiopia", phone: "251" },
  { code: "FI", label: "Finland", phone: "358" },
  { code: "FJ", label: "Fiji", phone: "679" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  { code: "FO", label: "Faroe Islands", phone: "298" },
  {
    code: "FR",
    label: "France",
    phone: "33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", phone: "241" },
  { code: "GB", label: "United Kingdom", phone: "44" },
  { code: "GD", label: "Grenada", phone: "1-473" },
  { code: "GE", label: "Georgia", phone: "995" },
  { code: "GF", label: "French Guiana", phone: "594" },
  { code: "GG", label: "Guernsey", phone: "44" },
  { code: "GH", label: "Ghana", phone: "233" },
  { code: "GI", label: "Gibraltar", phone: "350" },
  { code: "GL", label: "Greenland", phone: "299" },
  { code: "GM", label: "Gambia", phone: "220" },
  { code: "GN", label: "Guinea", phone: "224" },
  { code: "GP", label: "Guadeloupe", phone: "590" },
  { code: "GQ", label: "Equatorial Guinea", phone: "240" },
  { code: "GR", label: "Greece", phone: "30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", label: "Guatemala", phone: "502" },
  { code: "GU", label: "Guam", phone: "1-671" },
  { code: "GW", label: "Guinea-Bissau", phone: "245" },
  { code: "GY", label: "Guyana", phone: "592" },
  { code: "HK", label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", label: "Honduras", phone: "504" },
  { code: "HR", label: "Croatia", phone: "385" },
  { code: "HT", label: "Haiti", phone: "509" },
  { code: "HU", label: "Hungary", phone: "36" },
  { code: "ID", label: "Indonesia", phone: "62" },
  { code: "IE", label: "Ireland", phone: "353" },
  { code: "IL", label: "Israel", phone: "972" },
  { code: "IM", label: "Isle of Man", phone: "44" },
  { code: "IN", label: "India", phone: "91" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", label: "Iraq", phone: "964" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", label: "Iceland", phone: "354" },
  { code: "IT", label: "Italy", phone: "39" },
  { code: "JE", label: "Jersey", phone: "44" },
  { code: "JM", label: "Jamaica", phone: "1-876" },
  { code: "JO", label: "Jordan", phone: "962" },
  {
    code: "JP",
    label: "Japan",
    phone: "81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", phone: "254" },
  { code: "KG", label: "Kyrgyzstan", phone: "996" },
  { code: "KH", label: "Cambodia", phone: "855" },
  { code: "KI", label: "Kiribati", phone: "686" },
  { code: "KM", label: "Comoros", phone: "269" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  { code: "KR", label: "Korea, Republic of", phone: "82" },
  { code: "KW", label: "Kuwait", phone: "965" },
  { code: "KY", label: "Cayman Islands", phone: "1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", label: "Lebanon", phone: "961" },
  { code: "LC", label: "Saint Lucia", phone: "1-758" },
  { code: "LI", label: "Liechtenstein", phone: "423" },
  { code: "LK", label: "Sri Lanka", phone: "94" },
  { code: "LR", label: "Liberia", phone: "231" },
  { code: "LS", label: "Lesotho", phone: "266" },
  { code: "LT", label: "Lithuania", phone: "370" },
  { code: "LU", label: "Luxembourg", phone: "352" },
  { code: "LV", label: "Latvia", phone: "371" },
  { code: "LY", label: "Libya", phone: "218" },
  { code: "MA", label: "Morocco", phone: "212" },
  { code: "MC", label: "Monaco", phone: "377" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", label: "Montenegro", phone: "382" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", label: "Madagascar", phone: "261" },
  { code: "MH", label: "Marshall Islands", phone: "692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", label: "Mali", phone: "223" },
  { code: "MM", label: "Myanmar", phone: "95" },
  { code: "MN", label: "Mongolia", phone: "976" },
  { code: "MO", label: "Macao", phone: "853" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", label: "Martinique", phone: "596" },
  { code: "MR", label: "Mauritania", phone: "222" },
  { code: "MS", label: "Montserrat", phone: "1-664" },
  { code: "MT", label: "Malta", phone: "356" },
  { code: "MU", label: "Mauritius", phone: "230" },
  { code: "MV", label: "Maldives", phone: "960" },
  { code: "MW", label: "Malawi", phone: "265" },
  { code: "MX", label: "Mexico", phone: "52" },
  { code: "MY", label: "Malaysia", phone: "60" },
  { code: "MZ", label: "Mozambique", phone: "258" },
  { code: "NA", label: "Namibia", phone: "264" },
  { code: "NC", label: "New Caledonia", phone: "687" },
  { code: "NE", label: "Niger", phone: "227" },
  { code: "NF", label: "Norfolk Island", phone: "672" },
  { code: "NG", label: "Nigeria", phone: "234" },
  { code: "NI", label: "Nicaragua", phone: "505" },
  { code: "NL", label: "Netherlands", phone: "31" },
  { code: "NO", label: "Norway", phone: "47" },
  { code: "NP", label: "Nepal", phone: "977" },
  { code: "NR", label: "Nauru", phone: "674" },
  { code: "NU", label: "Niue", phone: "683" },
  { code: "NZ", label: "New Zealand", phone: "64" },
  { code: "OM", label: "Oman", phone: "968" },
  { code: "PA", label: "Panama", phone: "507" },
  { code: "PE", label: "Peru", phone: "51" },
  { code: "PF", label: "French Polynesia", phone: "689" },
  { code: "PG", label: "Papua New Guinea", phone: "675" },
  { code: "PH", label: "Philippines", phone: "63" },
  { code: "PK", label: "Pakistan", phone: "92" },
  { code: "PL", label: "Poland", phone: "48" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", label: "Pitcairn", phone: "870" },
  { code: "PR", label: "Puerto Rico", phone: "1" },
  {
    code: "PS",
    label: "Palestine, State of",
    phone: "970",
  },
  { code: "PT", label: "Portugal", phone: "351" },
  { code: "PW", label: "Palau", phone: "680" },
  { code: "PY", label: "Paraguay", phone: "595" },
  { code: "QA", label: "Qatar", phone: "974" },
  { code: "RE", label: "Reunion", phone: "262" },
  { code: "RO", label: "Romania", phone: "40" },
  { code: "RS", label: "Serbia", phone: "381" },
  { code: "RU", label: "Russian Federation", phone: "7" },
  { code: "RW", label: "Rwanda", phone: "250" },
  { code: "SA", label: "Saudi Arabia", phone: "966" },
  { code: "SB", label: "Solomon Islands", phone: "677" },
  { code: "SC", label: "Seychelles", phone: "248" },
  { code: "SD", label: "Sudan", phone: "249" },
  { code: "SE", label: "Sweden", phone: "46" },
  { code: "SG", label: "Singapore", phone: "65" },
  { code: "SH", label: "Saint Helena", phone: "290" },
  { code: "SI", label: "Slovenia", phone: "386" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", label: "Slovakia", phone: "421" },
  { code: "SL", label: "Sierra Leone", phone: "232" },
  { code: "SM", label: "San Marino", phone: "378" },
  { code: "SN", label: "Senegal", phone: "221" },
  { code: "SO", label: "Somalia", phone: "252" },
  { code: "SR", label: "Suriname", phone: "597" },
  { code: "SS", label: "South Sudan", phone: "211" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", label: "El Salvador", phone: "503" },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", label: "Swaziland", phone: "268" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", label: "Chad", phone: "235" },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
  },
  { code: "TG", label: "Togo", phone: "228" },
  { code: "TH", label: "Thailand", phone: "66" },
  { code: "TJ", label: "Tajikistan", phone: "992" },
  { code: "TK", label: "Tokelau", phone: "690" },
  { code: "TL", label: "Timor-Leste", phone: "670" },
  { code: "TM", label: "Turkmenistan", phone: "993" },
  { code: "TN", label: "Tunisia", phone: "216" },
  { code: "TO", label: "Tonga", phone: "676" },
  { code: "TR", label: "Turkey", phone: "90" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", label: "Tuvalu", phone: "688" },
  {
    code: "TW",
    label: "Taiwan",
    phone: "886",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", label: "Ukraine", phone: "380" },
  { code: "UG", label: "Uganda", phone: "256" },
  {
    code: "US",
    label: "United States",
    phone: "1",
    suggested: true,
  },
  { code: "UY", label: "Uruguay", phone: "598" },
  { code: "UZ", label: "Uzbekistan", phone: "998" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", label: "Venezuela", phone: "58" },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", label: "Vietnam", phone: "84" },
  { code: "VU", label: "Vanuatu", phone: "678" },
  { code: "WF", label: "Wallis and Futuna", phone: "681" },
  { code: "WS", label: "Samoa", phone: "685" },
  { code: "XK", label: "Kosovo", phone: "383" },
  { code: "YE", label: "Yemen", phone: "967" },
  { code: "YT", label: "Mayotte", phone: "262" },
  { code: "ZA", label: "South Africa", phone: "27" },
  { code: "ZM", label: "Zambia", phone: "260" },
  { code: "ZW", label: "Zimbabwe", phone: "263" },
];

